server:
  port: 0

spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/mailer_db
    username: root
    password: Password@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}